import Head from 'next/head';
import styles from './index.module.scss';
import Header from './components/layout/Header';
import Intro from './components/Intro';
import Posts from './components/Posts';
import Articles from './components/Articles';

export default function Home() {
	return (
		<>
			<Head>
				<title>News Homepage</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.png" />
			</Head>

			<Header />

			<main className={`${styles.main}`}>
				<div className="container">
					<div className={styles.mainDivision}>
						<Intro />
						<Posts />
					</div>

					<Articles />
				</div>
			</main>
		</>
	);
}
